services:
  glances:
    container_name: glances
    image: nicolargo/glances:3.2.7-full
    restart: always
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: --webserver

