- name: Install k3s server
  hosts: nexus_server
  become: yes
  tasks:
    - name: Download install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Run install script
      ansible.builtin.shell: >
        INSTALL_K3S_EXEC="
          --write-kubeconfig-mode 644
          --disable traefik
          --flannel-backend=host-gw
        "
        /tmp/k3s_install.sh
