- name: Uninstall k3s safely
  hosts: nexus
  become: yes
  tasks:
    - name: Check for server uninstall script
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: k3s_server_uninstall

    - name: Run server uninstall script
      ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
      when: k3s_server_uninstall.stat.exists

    - name: Check for agent uninstall script
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: k3s_agent_uninstall

    - name: Run agent uninstall script
      ansible.builtin.shell: /usr/local/bin/k3s-agent-uninstall.sh
      when: k3s_agent_uninstall.stat.exists
