- name: Install Docker to Debian
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
    - name: Install docker
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Create docker group
      ansible.builtin.group:
        name: docker
    - name: Add user to docker group
      user:
        name: arlo
        groups: docker
        append: yes

